version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "avisiedo"
    allowed_updates:
      - match:
          dependency_name: "@patternfly/*"
          dependency_type: "direct"
