# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
---
blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: mailto:alejandro.visiedo+sec-shell-lib@gmail.com
    about: Please report security vulnerabilities here.
