---
openapi: 3.0.0
info:
  title: ToDo API
  version: '1.0'
  description: API for managing ToDo items
  license:
    name: Apache
  tags:
    - name: todo
      description: Todo resource
paths:
  /todos:
    get:
      tags: [todo]
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ToDo'
          description: A list of ToDo items
      operationId: getAllTodos
      summary: Retrieve all ToDo items
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDoInput'
        required: true
      tags: [todo]
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
          description: The created ToDo item
      operationId: createTodo
      summary: Create a new ToDo item
  /todos/{todoId}:
    get:
      tags: [todo]
      parameters:
        - name: todoId
          description: ID of the item to Retrieve
          schema:
            format: uuid
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
          description: The ToDo item
      operationId: getTodo
      summary: Get item by ID
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDoInput'
        required: true
      tags: [todo]
      parameters:
        - name: todoId
          description: ID of the item to Retrieve
          schema:
            format: uuid
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
          description: The created ToDo item
      operationId: updateTodo
      summary: Substitute an existing ToDo item
    delete:
      tags: [todo]
      parameters:
        - name: todoId
          description: ID of the item to Retrieve
          schema:
            format: uuid
            type: string
          in: path
          required: true
      operationId: deleteTodo
      summary: Remove item by ID
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDoInputPatch'
        required: true
      tags: [todo]
      parameters:
        - name: todoId
          description: ID of the item to Retrieve
          schema:
            format: uuid
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
          description: The created ToDo item
      operationId: patchTodo
      summary: Patch an existing ToDo item
components:
  schemas:
    ToDo:
      required: [title, description]
      type: object
      properties:
        todo_id:
          format: uuid
          type: string
        title:
          type: string
        description:
          type: string
        due_date:
          format: date-time
          type: string
    ToDoInput:
      required: [title]
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        due_date:
          format: date
          type: string
    ToDoInputPatch:
      type: object
      properties:
        title:
          type: string
          optional: true
        description:
          type: string
          optional: true
        due_date:
          format: date
          type: string
          optional: true
